name: sedtrails

channels:
  - conda-forge
  
dependencies:
  - python=3.13
  - numpy
  - pandas
  - matplotlib
  - xarray
  - typer
  - pytest
  - flake8
  - sphinx=8.2.0
  - myst-parser=4.0.1
  - sphinx-rtd-theme
  - pyyaml
  - jsonschema
  - re
  - typing